base class overrides must be method, use NotImplementedError
Base class overridden attribute must be of type method
(function). If not then raise `NotImplementedError` for interface
class that does not implement the `@overrides` function.
Using `NotImplementedError` instead of `TypeError` is a more
accurate description of the problem.

Add appropriate pytests in test_overrides.py and
test_implements.py.

Add a few other related pytests.

See https://stackoverflow.com/a/54526724/471376